include $(THEOS)/makefiles/common.mk

ARCHS = armv7 armv7s arm64
CFLAGS = -fobjc-arc

BUNDLE_NAME = AppellancyFlipswitch
AppellancyFlipswitch_FILES = Switch.x
AppellancyFlipswitch_FRAMEWORKS = UIKit
AppellancyFlipswitch_LIBRARIES = flipswitch
AppellancyFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk